name: Attex
version: '${project.version}'
main: me.gonkas.attex.Attex
api-version: '1.20'

commands:
  chat:
    description: "Allows the user to switch chat channels."
  groupchat:
    description: "Basically WhatsApp but in Minecraft. No, you can't send images."